# Model predict

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('classification_df.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1423 entries, 0 to 1422
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userid     1423 non-null   int64
 1   rank-type  1423 non-null   object
 2   contest1   1423 non-null   int64
 3   contest2   1423 non-null   int64
 4   contest3   1423 non-null   int64
 5   contest4   1422 non-null   float64
 6   contest5   1404 non-null   float64
 7   contest6   1374 non-null   float64
 8   contest7   1343 non-null   float64
 9   contest8   1303 non-null   float64
 10  contest9   1279 non-null   float64
 11  contest10  1252 non-null   float64
dtypes: float64(7), int64(4), object(1)
memory usage: 133.5+ KB

# Data preprocessing

In [7]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype== 'object':
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
            df[col].fillna(df[col].mean(), inplace=True)

C:\Users\hamid\AppData\Local\Temp\ipykernel_10236\2327616410.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1423 entries, 0 to 1422
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userid     1423 non-null   int64
 1   rank-type  1423 non-null   object
 2   contest1   1423 non-null   int64
 3   contest2   1423 non-null   int64
 4   contest3   1423 non-null   int64
 5   contest4   1423 non-null   float64
 6   contest5   1423 non-null   float64
 7   contest6   1423 non-null   float64
 8   contest7   1423 non-null   float64
 9   contest8   1423 non-null   float64
 10  contest9   1423 non-null   float64
 11  contest10  1423 non-null   float64
dtypes: float64(7), int64(4), object(1)
memory usage: 133.5+ KB

In [9]:
df.head()

,userid,rank-type,contest1,contest2,contest3,contest4,contest5,contest6,contest7,contest8,contest9,contest10
0,3143927301,Candidate Master,2078,2055,2115,2047.0,2024.0,2010.0,1953.0,1936.0,2042.0,2045.0
1,1876577621,Master,2194,2114,2152,2179.0,2211.0,2154.0,2170.0,2141.0,2157.0,2209.0
2,6397741793,Master,2120,2206,2147,2234.0,2294.0,2090.0,2089.0,2072.0,2085.0,2114.0
3,3090123616,Master,2224,2222,2166,2116.0,2029.0,2113.0,2104.0,2096.0,2115.0,2163.0
4,9564162806,Master,2128,2120,2072,2018.0,1963.0,2039.0,1932.0,1963.0,1960.0,1886.0

In [10]:
df['rank-type'].value_counts()

rank-type
Master                        628
Candidate Master              411
Grandmaster                   159
International Master          120
International Grandmaster      87
Legendary Grandmaster          15
Pupil                           2
Newbie                          1
Name: count, dtype: int64

In [11]:
#Encoding
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns.drop('rank-type'):
    if df[col].dtype=='object':
        if df[col].nunique()<=3:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1423 entries, 0 to 1422
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userid     1423 non-null   int64
 1   rank-type  1423 non-null   object
 2   contest1   1423 non-null   int64
 3   contest2   1423 non-null   int64
 4   contest3   1423 non-null   int64
 5   contest4   1423 non-null   float64
 6   contest5   1423 non-null   float64
 7   contest6   1423 non-null   float64
 8   contest7   1423 non-null   float64
 9   contest8   1423 non-null   float64
 10  contest9   1423 non-null   float64
 11  contest10  1423 non-null   float64
dtypes: float64(7), int64(4), object(1)
memory usage: 133.5+ KB

In [13]:
df['rank-type']=encoder.fit_transform(df['rank-type'])

In [14]:
df.info(

)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1423 entries, 0 to 1422
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userid     1423 non-null   int64
 1   rank-type  1423 non-null   int64
 2   contest1   1423 non-null   int64
 3   contest2   1423 non-null   int64
 4   contest3   1423 non-null   int64
 5   contest4   1423 non-null   float64
 6   contest5   1423 non-null   float64
 7   contest6   1423 non-null   float64
 8   contest7   1423 non-null   float64
 9   contest8   1423 non-null   float64
 10  contest9   1423 non-null   float64
 11  contest10  1423 non-null   float64
dtypes: float64(7), int64(5)
memory usage: 133.5 KB

In [15]:
df.nunique()

userid       1423
rank-type       8
contest1      571
contest2      661
contest3      701
contest4      769
contest5      792
contest6      792
contest7      798
contest8      787
contest9      782
contest10     776
dtype: int64

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64', 'float64']).columns.drop('rank-type')
df[num_col]=scaler.fit_transform(df[num_col])

In [17]:
df.head()

,userid,rank-type,contest1,contest2,contest3,contest4,contest5,contest6,contest7,contest8,contest9,contest10
0,0.238008,0,0.412505,0.390950,0.467594,0.486448,0.472999,0.464768,0.460883,0.463612,0.477177,0.488870
1,0.097123,5,0.458120,0.412834,0.481142,0.533524,0.533832,0.507046,0.526941,0.525007,0.511712,0.536282
2,0.599720,5,0.429021,0.446958,0.479312,0.553138,0.560833,0.488256,0.502283,0.504343,0.490090,0.508818
3,0.232027,5,0.469917,0.452893,0.486269,0.511056,0.474626,0.495009,0.506849,0.511530,0.499099,0.522984
4,0.951717,5,0.432167,0.415059,0.451849,0.476106,0.453155,0.473282,0.454490,0.471698,0.452553,0.442903

# Model Training

In [18]:
x=df.drop('rank-type', axis=1)

In [19]:
y=df['rank-type']

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
x_train.shape, x_test.shape

((1138, 11), (285, 11))

In [23]:

y_train.shape, y_test.shape

((1138,), (285,))

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
model=LogisticRegression()

In [26]:
model

LogisticRegression()

In [27]:
model.fit(x_train, y_train)

C:\Users\hamid\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Predicting

In [28]:
y_pred=model.predict(x_test)

In [29]:
y_pred[1]

np.int64(0)

# Evaluation

In [30]:
from sklearn.metrics import accuracy_score, classification_report

In [31]:
score=accuracy_score(y_test,y_pred)

In [32]:
score

0.6210526315789474

In [33]:
report=classification_report(y_test,y_pred)

C:\Users\hamid\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\hamid\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\hamid\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [34]:
print(report)

              precision    recall  f1-score   support

           0       0.86      0.61      0.72        80
           1       0.68      0.38      0.49        45
           2       0.58      0.39      0.47        18
           3       0.00      0.00      0.00        27
           4       0.00      0.00      0.00         3
           5       0.55      0.93      0.69       112

    accuracy                           0.62       285
   macro avg       0.45      0.38      0.39       285
weighted avg       0.60      0.62      0.58       285

# Metrics

In [ ]:
#classification---accuracy_score, classifcation_report
#Regression------- r2(katta), mse,mae,rmse(kichik)

# Linear Regression

In [35]:
import pandas as pd

In [43]:
df=pd.read_csv('WineQT.csv')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [46]:
df['pH']

0       3.51
1       3.20
2       3.26
3       3.16
4       3.51
        ...
1138    3.42
1139    3.42
1140    3.45
1141    3.52
1142    3.57
Name: pH, Length: 1143, dtype: float64

In [50]:
# Encoding
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=3:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [54]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64', 'float64']).columns.drop('pH')
df[num_col]=scaler.fit_transform(df[num_col])

In [55]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,0.247788,0.397260,0.00,0.068493,0.106845,0.149254,0.098940,0.567548,3.51,0.137725,0.153846,0.4,0.000000
1,0.283186,0.520548,0.00,0.116438,0.143573,0.358209,0.215548,0.494126,3.20,0.209581,0.215385,0.4,0.000626
2,0.283186,0.438356,0.04,0.095890,0.133556,0.208955,0.169611,0.508811,3.26,0.191617,0.215385,0.4,0.001252
3,0.584071,0.109589,0.56,0.068493,0.105175,0.238806,0.190813,0.582232,3.16,0.149701,0.215385,0.6,0.001879
4,0.247788,0.397260,0.00,0.068493,0.106845,0.149254,0.098940,0.567548,3.51,0.137725,0.153846,0.4,0.002505

In [56]:
x=df.drop('pH', axis=1)

In [57]:
y=df['pH']

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [59]:
from sklearn.linear_model import LinearRegression

In [60]:
model=LinearRegression()

In [61]:
model

LinearRegression()

In [62]:
model.fit(x_train,y_train)

LinearRegression()

In [63]:
y_pred=model.predict(x_test)

In [64]:
y_pred

array([3.36715142, 3.4014903 , 3.39341411, 3.06136995, 3.23484956,
       3.2571891 , 3.23358289, 3.33571961, 3.37484325, 3.3105735 ,
       3.25393357, 3.34295285, 3.41824931, 3.35932378, 3.53910816,
       3.15081164, 3.15445887, 3.43235858, 3.24071214, 3.26193195,
       3.25658532, 3.22503505, 3.27392697, 3.43798509, 3.31905716,
       3.42391824, 3.21870281, 3.13552567, 3.1924923 , 3.35585013,
       3.41646138, 3.48375485, 2.976339  , 3.37537829, 3.35876171,
       3.24338725, 3.32087855, 3.14785224, 3.57270151, 3.28428238,
       3.20569341, 3.20309289, 3.61732361, 3.06610727, 3.3855736 ,
       3.41673502, 3.51636457, 3.22022011, 3.16516429, 3.44363394,
       3.27989481, 3.21757626, 3.41892088, 3.31660209, 3.3592148 ,
       3.00265753, 3.39067732, 3.50241833, 3.01255621, 3.49589686,
       3.14328736, 3.42854961, 3.39502957, 3.23145417, 3.36227846,
       3.34382492, 3.25779833, 3.35620332, 3.23285455, 3.16044763,
       2.83610014, 3.35265865, 3.40314895, 3.65671647, 3.21171861,
       3.3379487 , 3.3993889 , 3.25966183, 3.38729458, 3.4417633 ,
       3.41987543, 3.3685086 , 3.33110086, 3.38368076, 3.36117231,
       3.28887293, 3.42393618, 3.31727113, 3.34960312, 3.43328991,
       3.40955888, 3.39234377, 2.88435261, 3.2003392 , 3.320784  ,
       3.25132244, 3.44343138, 3.00208945, 3.32396208, 3.37312876,
       3.37176251, 3.58632773, 3.31063791, 3.44913156, 3.43189975,
       3.17958123, 3.30926982, 3.34467309, 3.37166484, 3.21011752,
       3.3444531 , 3.15503307, 3.10313858, 3.28378923, 3.23795051,
       3.34414556, 3.47284031, 3.29266889, 3.28186637, 3.15818596,
       3.35915494, 3.27984198, 3.3733125 , 3.1500139 , 3.36840354,
       3.3813477 , 3.33946826, 3.44960423, 3.04963286, 3.31494907,
       3.27050282, 3.50509442, 2.97884936, 3.41822518, 2.7964705 ,
       3.27833138, 3.23258946, 3.29106487, 3.33695242, 3.38715799,
       3.36829303, 3.37655643, 3.0205133 , 3.16040379, 3.19358382,
       3.458707  , 3.11228963, 3.34287521, 2.92423016, 3.29774629,
       3.18683383, 3.38108672, 3.06728792, 3.34270437, 3.53989069,
       3.33856098, 3.3428551 , 3.24183854, 3.26413637, 3.46113757,
       3.13540712, 3.23566767, 3.39264227, 3.43912316, 3.58545636,
       3.39232683, 3.01979615, 3.41283312, 3.49061766, 3.24653399,
       3.34756645, 3.47616796, 3.30080984, 3.39237443, 3.21955823,
       3.20579908, 3.16777491, 3.46086629, 3.27901619, 3.42222005,
       3.04568014, 3.07990614, 3.28342942, 3.34272458, 3.26553315,
       3.23402978, 3.18882379, 3.30301089, 3.08692301, 3.05919504,
       3.34560384, 3.24195868, 3.29167787, 3.08505661, 3.56457683,
       3.42620807, 3.42112996, 3.34884448, 3.23139498, 3.41230968,
       3.53477354, 3.34798944, 3.26652244, 3.43294063, 2.99055411,
       3.07888416, 3.28293146, 3.38353122, 3.38509665, 3.03883853,
       3.40367229, 3.15416981, 3.33951121, 3.45902081, 3.2322475 ,
       3.43024372, 3.336623  , 3.30572184, 3.19201936, 3.07612234,
       3.5821333 , 3.46299191, 3.35423534, 3.42141089, 3.55528256,
       3.31978902, 3.48351754, 3.13824047, 2.9830155 ])

In [65]:
from sklearn.metrics import r2_score, mean_squared_error

In [66]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [67]:
print(r2)
print(mse)

0.7265031437139704
0.007927861368256307